[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python="^3.11.9"
aiogram = "^3.13.1"
apscheduler = "^3.10.4"
sqlalchemy = "^2.0.35"
cachetools = "^5.5.0"
pydantic = "^2.9.2"
pydantic-settings = "^2.5.2"
asyncpg = "^0.29.0"
